# Generated by Django 6.0.1 on 2026-02-22 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_biometric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometric',
            name='id',
        ),
        migrations.AlterField(
            model_name='biometric',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.student', unique=True),
        ),
    ]
